// botbuilds.js — the gardener's seven hand-authored builds (CONTRACT §8).
// Each build is generated by deterministic code evaluated once at module load
// into a plain { name, blocks } shape: blocks = [[x, y, z, colorIndex], ...]
// in LOCAL island coords, ordered as a build sequence — foundations first,
// details next, glow lantern accents last — so every mid-state reads well
// from the 3/4 aerial view. Builds face +z (south), where visitors arrive.

const LIMIT_XZ = 11; // |x|, |z| bound for every block
const LIMIT_Y = 14; // y bound
const MIN_BLOCKS = 150;
const MAX_BLOCKS = 400;

// Palette indices (see PALETTE in world.js).
const WHITE = 0, SAND = 1, TERRA = 2, ROSE = 3, TWILIGHT = 5, TEAL = 6,
  SAGE = 7, HONEY = 9, RED = 11, COCOA = 12, SLATE = 13, INK = 14, GLOW = 15;

// ---------------------------------------------------------------------------
// Deterministic helpers — every shape derives from cell coordinates only.

// Per-cell hash in [0, 1) for stone speckle and other fixed texture.
function speckle(x, y, z) {
  let h = (Math.imul(x, 374761393) ^ Math.imul(y, 144665) ^ Math.imul(z, 668265263)) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

const pick = (c, x, y, z, d) => (typeof c === 'function' ? c(x, y, z, d) : c);

// Filled circle of cells at height y. Colors may be values or (x,y,z,d) fns.
function disc(stage, cx, cz, y, r, c) {
  for (let x = -LIMIT_XZ; x <= LIMIT_XZ; x++) {
    for (let z = -LIMIT_XZ; z <= LIMIT_XZ; z++) {
      const d = Math.hypot(x + 0.5 - cx, z + 0.5 - cz);
      if (d <= r) stage.push([x, y, z, pick(c, x, y, z, d)]);
    }
  }
}

// One-cell-thick circle (cylinder wall layer); skip(x,y,z) carves openings.
function ring(stage, cx, cz, y, rOut, thickness, c, skip) {
  for (let x = -LIMIT_XZ; x <= LIMIT_XZ; x++) {
    for (let z = -LIMIT_XZ; z <= LIMIT_XZ; z++) {
      const d = Math.hypot(x + 0.5 - cx, z + 0.5 - cz);
      if (d > rOut || d <= rOut - thickness) continue;
      if (skip && skip(x, y, z)) continue;
      stage.push([x, y, z, pick(c, x, y, z, d)]);
    }
  }
}

// Spherical shell slice between y0..y1 — domes and the balloon envelope.
function shell3(stage, cx, cy, cz, r, thickness, y0, y1, c, skip) {
  for (let y = Math.max(0, y0); y <= Math.min(LIMIT_Y, y1); y++) {
    for (let x = -LIMIT_XZ; x <= LIMIT_XZ; x++) {
      for (let z = -LIMIT_XZ; z <= LIMIT_XZ; z++) {
        const d = Math.hypot(x + 0.5 - cx, y + 0.5 - cy, z + 0.5 - cz);
        if (d > r || d <= r - thickness) continue;
        if (skip && skip(x, y, z)) continue;
        stage.push([x, y, z, pick(c, x, y, z, d)]);
      }
    }
  }
}

// Solid ellipsoid clipped to y >= 0 — the whale's resting body.
function blob(stage, cx, cy, cz, rx, ry, rz, c) {
  for (let y = 0; y <= LIMIT_Y; y++) {
    for (let x = -LIMIT_XZ; x <= LIMIT_XZ; x++) {
      for (let z = -LIMIT_XZ; z <= LIMIT_XZ; z++) {
        const qx = (x + 0.5 - cx) / rx;
        const qy = (y + 0.5 - cy) / ry;
        const qz = (z + 0.5 - cz) / rz;
        if (qx * qx + qy * qy + qz * qz <= 1) stage.push([x, y, z, pick(c, x, y, z, 0)]);
      }
    }
  }
}

// Axis-aligned filled box; skip carves doors and windows.
function box(stage, x0, x1, y0, y1, z0, z1, c, skip) {
  for (let y = y0; y <= y1; y++) {
    for (let x = x0; x <= x1; x++) {
      for (let z = z0; z <= z1; z++) {
        if (skip && skip(x, y, z)) continue;
        stage.push([x, y, z, pick(c, x, y, z, 0)]);
      }
    }
  }
}

// Hollow rectangular wall ring between (x0..x1, z0..z1) for y0..y1.
function walls(stage, x0, x1, y0, y1, z0, z1, c, skip) {
  box(stage, x0, x1, y0, y1, z0, z1, c, (x, y, z) =>
    (x !== x0 && x !== x1 && z !== z0 && z !== z1) || (skip && skip(x, y, z)));
}

function column(stage, x, z, y0, y1, c) {
  for (let y = y0; y <= y1; y++) stage.push([x, y, z, pick(c, x, y, z, 0)]);
}

// Explicit hand-placed cells, one shared color.
function put(stage, c, cells) {
  for (const [x, y, z] of cells) stage.push([x, y, z, c]);
}

// Two-tone stone speckle.
const stone = (a, b, p) => (x, y, z) => (speckle(x, y, z) < p ? a : b);

// Sort each stage bottom-up, then sweep around the build center so layers
// grow as rising spirals; dedupe across stages (first writer wins); enforce
// the contract bounds and block budget. Throws only on authored data drift.
function assemble(name, cx, cz, stages) {
  const seen = new Set();
  const blocks = [];
  for (const stage of stages) {
    stage.sort((a, b) =>
      a[1] - b[1] ||
      Math.atan2(a[2] + 0.5 - cz, a[0] + 0.5 - cx) -
        Math.atan2(b[2] + 0.5 - cz, b[0] + 0.5 - cx) ||
      a[0] - b[0] || a[2] - b[2]);
    for (const b of stage) {
      const k = b[0] + ',' + b[1] + ',' + b[2];
      if (seen.has(k)) continue;
      seen.add(k);
      if (Math.abs(b[0]) > LIMIT_XZ || Math.abs(b[2]) > LIMIT_XZ || b[1] < 0 || b[1] > LIMIT_Y) {
        throw new Error(`botbuilds: "${name}" block out of bounds at ${k}`);
      }
      blocks.push(b);
    }
  }
  if (blocks.length < MIN_BLOCKS || blocks.length > MAX_BLOCKS) {
    throw new Error(`botbuilds: "${name}" has ${blocks.length} blocks`);
  }
  return { name, blocks };
}

// ---------------------------------------------------------------------------
// 1. The lighthouse — banded Brick Red / Cloud White tower on a rocky base,
// keeper's hut alongside, glow lantern room lit last.

function lighthouse() {
  const base = [];
  disc(base, 0, 0, 0, 4.3, stone(SLATE, SAND, 0.6));
  disc(base, 0, 0, 1, 3.4, stone(SLATE, SAND, 0.55));

  const tower = [];
  const door = (x, y, z) => y <= 3 && z >= 2 && (x === -1 || x === 0);
  for (let y = 2; y <= 10; y++) {
    const band = ((y - 2) >> 1) % 2 === 0 ? RED : WHITE;
    ring(tower, 0, 0, y, 2.85 - 0.07 * (y - 2), 1.1, band, door);
  }

  const gallery = [];
  disc(gallery, 0, 0, 11, 3.2, SLATE);
  put(gallery, SLATE, [[1, 12, 1], [-2, 12, 1], [1, 12, -2], [-2, 12, -2]]);

  const cap = [];
  disc(cap, 0, 0, 13, 2.4, SLATE);
  disc(cap, 0, 0, 14, 1.3, SLATE);

  const hut = [];
  walls(hut, 4, 6, 0, 1, 3, 5, WHITE, (x, y, z) => x === 4 && z === 4);
  box(hut, 4, 6, 2, 2, 3, 5, SLATE);

  const lantern = [];
  ring(lantern, 0, 0, 12, 1.9, 1.2, GLOW);

  return assemble('the lighthouse', 0, 0, [base, tower, gallery, cap, hut, lantern]);
}

// ---------------------------------------------------------------------------
// 2. The sleeping whale — Twilight Blue back over a Teal belly, lying
// broadside to the south, flukes raised, a glowing spout caught mid-breath.

function whale() {
  const hide = (x, y, z) => (y < 2 ? TEAL : TWILIGHT);
  const body = [];
  blob(body, -1.5, 1.2, -0.5, 8, 3.4, 3, hide);

  const tail = [];
  box(tail, 6, 7, 2, 2, -1, 0, TWILIGHT);
  box(tail, 8, 8, 3, 3, -1, 0, TWILIGHT);
  // flukes: a raised V spreading in z, tips upturned
  put(tail, TWILIGHT, [
    [9, 4, -3], [9, 4, -2], [9, 4, -1], [9, 4, 0], [9, 4, 1], [9, 4, 2],
    [10, 4, -4], [10, 4, -3], [10, 4, 2], [10, 4, 3],
    [10, 5, -5], [10, 5, 4],
  ]);

  const flipper = [];
  put(flipper, TEAL, [[-4, 1, 3], [-3, 1, 3], [-2, 1, 3], [-3, 0, 4]]);

  const eye = [];
  put(eye, INK, [[-7, 2, 2]]); // closed eye, proud of the hide — fast asleep

  const spout = [];
  put(spout, WHITE, [[-6, 4, -1], [-6, 5, -1]]);

  const sparkle = [];
  put(sparkle, GLOW, [[-6, 6, -1], [-5, 5, -1], [-7, 6, 0]]);

  return assemble('the sleeping whale', -1.5, -0.5, [body, tail, flipper, eye, spout, sparkle]);
}

// ---------------------------------------------------------------------------
// 3. The tea house — Terracotta walls on a Sandstone plinth, Cocoa pagoda
// roof with upturned eaves, Honey windows, two glow lanterns by the door.

function teaHouse() {
  const plinth = [];
  box(plinth, -4, 4, 0, 0, -3, 3, SAND);
  put(plinth, SAND, [[0, 0, 4], [0, 0, 5]]); // stepping stones to the door

  const frame = [];
  for (const [x, z] of [[-3, -2], [3, -2], [-3, 2], [3, 2]]) column(frame, x, z, 1, 3, COCOA);

  const wall = [];
  const door = (x, y, z) => z === 2 && x === 0 && y <= 2;
  const window = (x, y, z) => y === 2 &&
    ((Math.abs(x) === 2 && Math.abs(z) === 2) || (Math.abs(x) === 3 && z === 0));
  walls(wall, -3, 3, 1, 3, -2, 2,
    (x, y, z) => (window(x, y, z) ? HONEY : TERRA), door);

  const roof = [];
  box(roof, -4, 4, 4, 4, -3, 3, COCOA);
  box(roof, -3, 3, 5, 5, -2, 2, COCOA);
  box(roof, -2, 2, 6, 6, -1, 1, COCOA);
  box(roof, -1, 1, 7, 7, 0, 0, COCOA);
  put(roof, COCOA, [[5, 5, 4], [-5, 5, 4], [5, 5, -4], [-5, 5, -4]]); // upturned eaves

  const porch = [];
  column(porch, 2, 4, 1, 2, COCOA);
  column(porch, -2, 4, 1, 2, COCOA);

  const lanterns = [];
  put(lanterns, GLOW, [[2, 3, 4], [-2, 3, 4]]);

  return assemble('the tea house', 0, 0, [plinth, frame, wall, roof, porch, lanterns]);
}

// ---------------------------------------------------------------------------
// 4. The observatory — Cloud White drum under a Slate dome, a Honey-lit slit
// rolling up from the south horizon, a Cocoa telescope nosing through.

function observatory() {
  const base = [];
  disc(base, 0, 0, 0, 3.8, stone(SAND, SLATE, 0.7));

  const drum = [];
  const door = (x, y, z) => y <= 2 && z >= 2 && (x === -1 || x === 0);
  for (let y = 1; y <= 6; y++) ring(drum, 0, 0, y, 3.0, 1.1, stone(WHITE, SAND, 0.82), door);

  const terrace = [];
  ring(terrace, 0, 0, 7, 3.7, 1.0, SLATE);

  const dome = [];
  const slit = (x, y, z) => (x === -1 || x === 0) && z >= -1;
  shell3(dome, 0, 7.5, 0, 3.5, 1.2, 7, 11,
    (x, y, z) => (slit(x, y, z) ? HONEY : SLATE));

  const scope = [];
  put(scope, COCOA, [
    [-1, 9, 2], [0, 9, 2], [-1, 10, 3], [0, 10, 3], [-1, 11, 4], [0, 11, 4],
  ]);

  const lamps = [];
  put(lamps, GLOW, [[1, 1, 3], [-2, 1, 3]]);

  return assemble('the observatory', 0, 0, [base, drum, terrace, dome, scope, lamps]);
}

// ---------------------------------------------------------------------------
// 5. The hot-air balloon — Cocoa basket, Sandstone ropes, then the envelope
// inflates layer by layer in Rose Clay / Honey stripes; burner lit last.

function balloon() {
  const basket = [];
  box(basket, -1, 1, 0, 0, -1, 1, COCOA);
  walls(basket, -1, 1, 1, 1, -1, 1, COCOA);

  const ropes = [];
  for (const [x, z] of [[-1, -1], [1, -1], [-1, 1], [1, 1]]) column(ropes, x, z, 2, 4, SAND);

  const throat = [];
  ring(throat, 0, 0, 4, 2.3, 1.0, COCOA);

  const envelope = [];
  const stripes = (x, y, z) => {
    const sector = Math.floor((Math.atan2(z + 0.5, x + 0.5) + Math.PI) / (Math.PI / 4));
    return sector % 2 === 0 ? ROSE : HONEY;
  };
  shell3(envelope, 0, 9.5, 0, 4.5, 1.2, 5, 14, stripes);

  const burner = [];
  put(burner, GLOW, [[0, 2, 0], [0, 3, 0]]);

  return assemble('the hot-air balloon', 0, 0, [basket, ropes, throat, envelope, burner]);
}

// ---------------------------------------------------------------------------
// 6. The giant sunflower — Sage stem and leaves, a great Honey-petalled face
// turned south, two small companions, one firefly glow at the heart.

function sunflower() {
  const mound = [];
  disc(mound, 0.5, 0.5, 0, 2.2, COCOA);

  const stem = [];
  column(stem, 0, 0, 0, 8, SAGE);

  const leaves = [];
  put(leaves, SAGE, [
    [1, 3, 0], [2, 3, 0], [2, 3, 1], [3, 4, 1],
    [-1, 5, 0], [-2, 5, 0], [-2, 5, -1], [-3, 6, -1],
  ]);

  // The face lives in the x/y plane at z = 1 (backing plate at z = 0).
  const headCell = (x, y) => Math.hypot(x, y - 9.5);
  const back = [];
  for (let y = 6; y <= 13; y++) {
    for (let x = -4; x <= 4; x++) {
      if (headCell(x, y) <= 3.2) back.push([x, y, 0, SAGE]);
    }
  }
  const core = [];
  const petals = [];
  for (let y = 5; y <= 14; y++) {
    for (let x = -4; x <= 4; x++) {
      const d = headCell(x, y);
      if (d <= 2.0) core.push([x, y, 1, COCOA]);
      else if (d <= 4.2) petals.push([x, y, 1, HONEY]);
    }
  }
  const spikes = [];
  put(spikes, HONEY, [
    [5, 9, 1], [5, 10, 1], [-5, 9, 1], [-5, 10, 1], [0, 14, 1], [0, 5, 1],
    [4, 13, 1], [-4, 13, 1], [4, 6, 1], [-4, 6, 1],
  ]);

  const companions = [];
  column(companions, 5, 3, 0, 4, SAGE);
  put(companions, COCOA, [[5, 5, 4]]);
  put(companions, HONEY, [
    [4, 5, 4], [6, 5, 4], [5, 4, 4], [5, 6, 4],
    [4, 4, 4], [6, 6, 4], [4, 6, 4], [6, 4, 4],
  ]);
  column(companions, -5, -2, 0, 2, SAGE);
  put(companions, COCOA, [[-5, 3, -1]]);
  put(companions, HONEY, [[-6, 3, -1], [-4, 3, -1], [-5, 2, -1], [-5, 4, -1]]);

  const grass = [];
  put(grass, SAGE, [[-3, 0, 2], [3, 0, -2], [-2, 0, -3], [2, 0, 3], [-4, 0, -1]]);

  const firefly = [];
  put(firefly, GLOW, [[0, 10, 2], [6, 6, 5]]);

  return assemble('the giant sunflower', 0.5, 0.5,
    [mound, stem, leaves, back, core, petals, spikes, companions, grass, firefly]);
}

// ---------------------------------------------------------------------------
// 7. The stone arch bridge — Slate and Sandstone spanning a recess implied by
// its own stepped causeways, arch first, deck after, lantern caps at dusk.

function bridge() {
  const archY = (x) => {
    const u = x / 7.2; // cell-symmetric around x = 0, like the deck above it
    return u * u >= 1 ? 0 : 4.6 * Math.sqrt(1 - u * u);
  };
  const mix = stone(SLATE, SAND, 0.62);

  const abutments = [];
  box(abutments, 8, 9, 0, 4, -1, 1, mix);
  box(abutments, -9, -8, 0, 4, -1, 1, mix);
  box(abutments, 10, 10, 0, 3, -1, 1, mix); // stepped causeway down to the grass
  box(abutments, 11, 11, 0, 1, -1, 1, mix);
  box(abutments, -10, -10, 0, 3, -1, 1, mix);
  box(abutments, -11, -11, 0, 1, -1, 1, mix);

  const spandrel = [];
  for (let x = -7; x <= 7; x++) {
    const open = archY(x);
    for (let y = 0; y <= 4; y++) {
      if (y + 0.5 <= open) continue; // the arch opening
      for (let z = -1; z <= 1; z++) spandrel.push([x, y, z, mix(x, y, z)]);
    }
  }

  const deck = [];
  box(deck, -9, 9, 5, 5, -1, 1, (x, y, z) => (z === 0 ? SAND : mix(x, y, z)));

  const rails = [];
  for (let x = -9; x <= 9; x += 3) {
    rails.push([x, 6, -1, SLATE], [x, 6, 1, SLATE]);
  }

  const lanterns = [];
  put(lanterns, GLOW, [[-9, 7, -1], [-9, 7, 1], [0, 7, -1], [0, 7, 1], [9, 7, -1], [9, 7, 1]]);

  return assemble('the stone arch bridge', 0, 0, [abutments, spandrel, deck, rails, lanterns]);
}

// ---------------------------------------------------------------------------

export const BOT_BUILDS = [
  lighthouse(),
  whale(),
  teaHouse(),
  observatory(),
  balloon(),
  sunflower(),
  bridge(),
];
